id: A49EC9E71
base_file: fCC44.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:48:34.624478
  last_modified_at: 2022-06-19 17:48:34.624481
