id: A49EC9E71
base_file: f8B8F.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:48:34.621486
  last_modified_at: 2022-06-19 17:48:34.621490
