id: A49EC9E71
base_file: fA76C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:48:34.622777
  last_modified_at: 2022-06-19 17:48:34.622780
