id: A49EC9E71
base_file: f0A38.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:48:34.617378
  last_modified_at: 2022-06-19 17:48:34.617386
